### ISSUE TITLE
Formtastic constant error

### ISSUE THREAD

**Issue by tparsnick** [HeHStudy/surveyor#61]
**issue:**  Intermittantly we see a Formtastic error when developing: `Unable to autoload constant Surveyor::Helpers::FormtasticCustomInput, expected /usr/local/bundle/bundler/gems/surveyor-a526f7bea63b/lib/surveyor/helpers/formtastic_custom_input.rb to define it (LoadError)`

**plan:**  Create a branch fix_unable_to_autoload_helper_constants to handle this problem.

**Comment by tparsnick** [comment]
I have used the branch and got the error on the rails console
```

root@1abc698a8ed7:/webapps/app# bundle exec rails c
requiring...: /usr/local/bundle/bundler/gems/surveyor-a526f7bea63b/lib/surveyor/helpers/surveyor_helper_methods.rb
requiring...: /usr/local/bundle/bundler/gems/surveyor-a526f7bea63b/lib/surveyor/helpers/formtastic_custom_input.rb
/usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:495:in `load_missing_constant': Unable to autoload constant Surveyor::Helpers::FormtasticCustomInput, expected /usr/local/bundle/bundler/gems/surveyor-a526f7bea63b/lib/surveyor/helpers/formtastic_custom_input.rb to define it (LoadError)
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
	from /usr/local/bundle/bundler/gems/surveyor-a526f7bea63b/app/inputs/surveyor_check_boxes_input.rb:2:in `<class:SurveyorCheckBoxesInput>'
	from /usr/local/bundle/bundler/gems/surveyor-a526f7bea63b/app/inputs/surveyor_check_boxes_input.rb:1:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:457:in `load'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:456:in `load_file'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:317:in `depend_on'
	from /usr/local/bundle/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:233:in `require_dependency'
```
